### ISSUE TITLE
Problème lors de la création d'une candidature Accès controlé

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-ecandidat#1]
Lorsqu'on crée une candidature sur une formation Accès controlé, le candidat reçoit le mail CANDIDATURE et sa candidature (coté gestionnaire) n'est pas validée.
Pour que le candidat puisse déposer ses documents, il doit attendre que le gestionnaire valide sa candidature, ce qui est long à traiter avec le grand nombre de candidatures possible sur une formation Accès controlé.
Ce fonctionnement d'attente de validation du type de traitement n'a de sens que pour l'Accès direct puisque ce type de traitement peut au final être un Accès controlé, mais pas l'inverse.

Il faudrait donc distinguer les cas Accès controlé et Accès direct et faire en sorte que : 
- si c'est une formation Accès controlé, la candidature est automatiquement validée et le candidat reçoit le mail TYPE_TRAIT_AC
- si c'est une formation Accès direct, la candidature reste non validée et le candidat reçoit le mail CANDIDATURE

**Comment by khergalant** [comment]
Bonjour,
Une prochaine évolution validera automatiquement le type de traitement en Accès contrôlé.
Par contre le mail envoyé sera toujours "CANDIDATURE".
Cordialement,
