### ISSUE TITLE
Problème avec les PJ

### ISSUE THREAD

**Issue by LuMadr** [EsupPortail/esup-ecandidat#10]
Bonjour,
Peu importe le type de ficher (PDF, JPG), le message "Erreur lors du chargement du fichier" s'affiche en rouge et par dessus un autre message "erreur à la création du fichier" apparaît également. Pourtant mes fichiers n'excèdent pas la taille demandée. 
Est-ce un problème lié au site ?

**Comment by ChrystelleG** [comment]
Je suis dans le même cas que toi, impossible de télécharger le moindre fichier...

**Comment by LuMadr** [comment]
J'espère qu'ils résoudront ce problème le plus rapidement possible...

**Comment by ChrystelleG** [comment]
Dernier délais jusqu'à demain pour mes dossiers, l'angoisse...

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,
