### ISSUE TITLE
Problème connexion

### ISSUE THREAD

**Issue by nelly38** [EsupPortail/esup-ecandidat#11]
Je me suis crée un compte e candidat il y a quelques semaines, pour candidater en L2 Musicologie. Depuis une semaine, je n'arrive plus à me connecter : dès que je rentre mon login, le serveur me dit que cela ne correspond à aucune campagne en cours.
Je m'étais pourtant inscrite et avais commencé à remplir des informations.

Merci d'avance,

Denurra Nelly

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,

**Comment by nelly38** [comment]
Bonjour, 

Merci de votre réponse. Cependant, j'ai déjà téléphoné directement à mon université Lyon2, mais ils m'ont dit de voir cela avec l'assistance. 
Je ne sais pas qui contacter d'autre. 

Cordialement, 

Denurra Nelly 

----- Mail original -----

De: "Kevin Hergalant" <notifications@github.com> 
À: "EsupPortail/esup-ecandidat" <esup-ecandidat@noreply.github.com> 
Cc: "nelly38" <nelly.denurra@laposte.net>, "Author" <author@noreply.github.com> 
Envoyé: Vendredi 14 Juin 2019 12:30:01 
Objet: Re: [EsupPortail/esup-ecandidat] Problème connexion (#11) 



Bonjour, 

Vous n'êtes pas au bon endroit pour ce genre de demande. 
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté. 

Cordialement,
