### ISSUE TITLE
Interfaçage Ecandidat - Helpdesk

### ISSUE THREAD

**Issue by Piochelle** [EsupPortail/esup-ecandidat#14]
Bonjour,

Nous utilisons dans notre établissement (université de Rouen) Ecandidat pour les candidatures des étudiants sur nos formations, mais aussi le helpdesk (que nous avons pour l'occasion rebaptisé localement en Helpetu) qui nous permet de traiter les questions des étudiants sur leurs problèmes liés à la scolarité et autres sujets. Actuellement, toutes les questions concernant ecandidat sont posées via des adresses mails de contact inclues dans Ecandidat. Nous souhaiterions qu'au lieu de passer par des mails les étudiants puissent formuler leurs questions, réclamations, etc... via des tickets (questions) sur notre helpetu. Cela nous permettrait de sécuriser ces échanges (risques de spam, mails non délivrés, SVA...) en ayant pour chaque question/réclamation une bonne traçabilité des échanges.

Serait-il possible d'ajouter cette possibilité dans Ecandidat dans une prochaine version ?

Je suis à votre disposition pour toute question à ce sujet.

Cordialement.

**Comment by khergalant** [comment]
Bonjour,

Qu'entendez vous par interfaçage?
Si c'est ajouter un lien dans la page d'assistance à destination des candidats, c'est faisable.

Cordialement,

**Comment by Piochelle** [comment]
Bonjour,

Il nous faudrait en fait un champ supplémentaire lié à chaque commission 
permettant de saisir une URL pointant vers une catégorie du helpetu 
spécifique. En parallèle, il nous faudrait avoir la possibilité de 
masquer l'adresse mail e contact qui permet d'avertir le gestionnaire 
d'une action du candidat.
L'accès au helpetu existe déjà dans la partie assistance de Ecandidat, 
mais c'est pour la partie contact avec la commission que nous 
souhaiterions avoir cette fonctionnalité.

Cordialement.

Le 14/11/2019 à 15:20, Kevin Hergalant a écrit :

**Comment by khergalant** [comment]
Bonjour,

Je vais voir pour ajouter une url pour la commission.

Cordialement,

**Comment by khergalant** [comment]
Bonjour,

Cela a été ajouté dans la 2.3.2.

Cordialement,
