### ISSUE TITLE
Problème des mises à jour en masse des formations

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-ecandidat#15]
Bonjour,
Nous sommes en train de tester les délais de confirmation et dans ce but, j'ai voulu mettre à jour un ensemble de formation.
Le problème est que les délais de confirmation n'ont pas été sauvegardé alors que j'avais renseigné le champs.
Merci de corriger ce bug et de vérifier que d'autres champs ne sont pas impactés.
Cordialement,
Yoann Lecuyer

**Comment by khergalant** [comment]
Bonjour,

Il y a effectivement un bug concernant les délais.

Cela sera corrigé à la prochaine livraison.

Cordialement,

**Comment by khergalant** [comment]
Bonjour,

Ce bug est corrigé dans la 2.3.2.

Cordialement,
