### ISSUE TITLE
Ajout utilisateur hors ldap organisation

### ISSUE THREAD

**Issue by svaysset** [EsupPortail/esup-ecandidat#16]
Bonjour,
le cadre de formation en co-accrédiation à l'INSA Toulouse, nous avons besoin de déclarer des utilisateurs hors INSA. N'appartenant pas à notre LDAP, nous devons les ajouter directement en base.
Est il possible d'ajouter cette fonctionnalité dans la composition des utilisateurs d'un centre de candidature ?
Cordialement

Sylvain Vaysset
INSA Toulouse

**Comment by ElZorrito** [comment]
Bonjour,

Cette fonctionnalité n'est pas prévue.

Cordialement,

**Comment by khergalant** [comment]
Bonjour,

Cette fonctionnalité n'est pas prévue.

Cordialement,
