### ISSUE TITLE
Problème d'accents dans les sujets des emails

### ISSUE THREAD

**Issue by cardon-matthieu** [EsupPortail/esup-ecandidat#17]
Bonjour.

Quand j'utilise un caractère accentué dans un sujet d'email il est remplacé par un point d'interrogation.
J'ai vérifié en base de données, il est bien présent.
Aucun soucis par contre pour le corps du message, les accents sont bien présents.

Cordialement,
Matthieu Cardon
Université de Lille.

**Comment by khergalant** [comment]
Bonjour,

Quelle version de ecandidat utilisez vous?

Cordialement,

**Comment by cardon-matthieu** [comment]
C'est la version 2.3.1 issue de la branche Master du dépôt GIT.

**Comment by khergalant** [comment]
Je ne reproduis pas le bug.
C'est pendant l'édition ou une fois que vous avez édité et que vous ré-ouvrez l'édition du mail?

**Comment by cardon-matthieu** [comment]
Nous avons paramétré l'email comme cela :

![01](https://user-images.githubusercontent.com/59964611/72898683-d8954680-3d24-11ea-8f38-654a236e8f33.png)

On peut voir en base de données que c'est correct :+1: 

![02](https://user-images.githubusercontent.com/59964611/72898753-f8c50580-3d24-11ea-98ca-ca23ab78f40f.png)

Je procède ensuite à une création d'un compte dans l'appli pour recevoir l'email de confirmation.
L'email qui arrive a ce sujet : 

![03](https://user-images.githubusercontent.com/59964611/72898883-388bed00-3d25-11ea-8282-1a1335191331.png)

On peut voir dans la source de l'email que c'est bien un point d'interrogation qui est à la place du 'é' : 

![04](https://user-images.githubusercontent.com/59964611/72898938-535e6180-3d25-11ea-8868-af4898747c31.png)

**Comment by khergalant** [comment]
Je n'avais pas compris que c'était dans le mail lui-même.
Ne pouvant reproduire le problème, êtes vous d'accord pour modifier le code que je vous fournirai pour tester et essayer de résoudre ce problème?

**Comment by khergalant** [comment]
Si oui, modifiez le fichier src/main/java/fr/univlorraine/ecandidat/controllers/MailController.java, ligne 339 et remplacez :
message.setSubject(title);
par
message.setSubject(title, "utf-8");

Recompilez et déployez à nouveau.
Tenez moi au courant.

Cordialement,

**Comment by cardon-matthieu** [comment]
Bonjour.
Le correctif fonctionne parfaitement.
Merci pour votre réactivité.

Cordialement,
Matthieu Cardon / Université de Lille.

**Comment by khergalant** [comment]
Bonjour,

Bonne nouvelle! Cela sera livré dans la prochaine version 2.3.2.

Cordialement,
