### ISSUE TITLE
Dates Licences

### ISSUE THREAD

**Issue by Ailu117** [EsupPortail/esup-ecandidat#18]
Bonjour,

Pour l'inscription 2020-2021 en Licence, je pense que les dates pour candidater n'ont pas été mises a jour. De ce fait, il est impossible de remplir les dossiers correspondants a la licence désirée. En effet, les inscriptions débutent le 18/02/2019 ce qui parait tôt pour cette session.

Merci si vous avez des informations a ce sujet

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,
