### ISSUE TITLE
Je ne peux pas saisir mes informations

### ISSUE THREAD

**Issue by Lucas-FRUET** [EsupPortail/esup-ecandidat#19]
Je me suis déconnecter de mon esapce et dès que je my reconnecte je ne pas pas saisir les informations de mon cursus externe j'ai ce message d'affiché "Ces données sont en cours d'utilisation, vous ne pouvez pas les modifier"

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,
