### ISSUE TITLE
Utilisation du régime d'inscription pour l'OPI

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-ecandidat#20]
Bonjour,
Suite à la prise en main de notre SFCA sur la plateforme Candidatures, il apparait qu'on voudrait distinguer dans nos OPI les candidats ayant un régime d'inscription FC pour qu'ils puissent disposer de frais d'inscription particuliers.
Je constate que le régime renseigné via l'écran d'administration ne sert à rien mis à part pour les exports.
Serait-il possible de mettre en place un paramétrage qui si on définit le code du régime pour les candidats FC, puisse être repris lors du déversement de l'OPI ?
Merci d'avance.
Yoann Lecuyer

**Comment by khergalant** [comment]
Bonjour,

Je vais regarder si c'est rapide à faire.

Cordialement,

**Comment by yoannlecuyer** [comment]
Bonjour Kevin,
Merci pour ce retour d'info.
De notre coté, nous avons procédé sans cet élément pour distinguer les candidats FC, en utilisant des scripts.
Pour info, nous avons une plateforme FC dédié et une plateforme FI/FA avec des populations mixtes.
Sera-t-il possible, pour la 1ère plateforme, de définir le témoin FC par défaut ?
Pour la 2nde, sera-t-il possible de mettre à jour le champs en masse ?
Cordialement,
Yoann

**Comment by khergalant** [comment]
Hello Yoann,

Pour info, la possibilité de placer le témoin FC sur une candidature sera bientôt possible.
Je clos ce ticket du coup.

Cordialement,
