### ISSUE TITLE
Dossiers en PDF s'ouvrant à la page 2020-DIRSCO-FC

### ISSUE THREAD

**Issue by cardon-matthieu** [EsupPortail/esup-ecandidat#21]
Bonjour.

Quand on ouvre le fichier PDF généré par l'application (Télécharger mon dossier) avec le lecteur officiel de chez Adobe (Acobat Reader DC 20.006.20042) il s'ouvre directement à la page 2020-DIRSCO-FC au lieu de la page n°1.

D'autre lecteurs PDF ne présentent pas ce comportement mais ils ne sont peut être pas compatibles avec la directive "Open to page".

Comment faire pour que les fichiers PDF n'aient pas cette directive ?

Cordialement,
Matthieu Cardon
Université de Lille.

**Comment by khergalant** [comment]
Bonjour,

Désolé mais je ne reproduis pas le problème.

Cordialement,
