### ISSUE TITLE
Candidatures et comptes désactivés

### ISSUE THREAD

**Issue by cardon-matthieu** [EsupPortail/esup-ecandidat#22]
Bonjour.

Nous avons des soucis avec des étudiants non inscrits en 2019-2020 qui commencent leurs candidatures via une connexion CAS car leurs comptes sont encore actifs (étudiants en 2018-
2019)  alors que ne nous indiquons que seul les étudiants inscrits en 2019-2020 doivent passer par le CAS.

Après quelques mois les comptes sont désactivés et il ne peuvent plus accéder à leurs candidatures.

Quelle serait la bonne démarche pour ces candidats ?
Les identifier, leur demander la création d'un compte local et transférer les données de la candidature sur ce nouveau compte ?
Avez-vous des cas similaires ?

Cordialement,
Matthieu Cardon
Université de Lille.

**Comment by khergalant** [comment]
Bonjour,

Ces candidats peuvent accéder à leur compte avec leur login/mdp créer à l'inscription.

Cordialement,
