### ISSUE TITLE
URGENT problème E-candidat - impossible de candidater

### ISSUE THREAD

**Issue by NSEVA** [EsupPortail/esup-ecandidat#23]
Madame, Monsieur,

Je me permets de vous contacter suite à un problème constater sur la plateforme e-candidat Lyon 2.
En effet, étant étudiante à Lyon 2, il me suffit normalement de me connecter pour voir l'ensemble de mon profil (parcours, cursus) s'afficher.
Néanmoins, ce n'est pas le cas actuellement. En effet, lors de la connexion, la plateforme ne reconnaît uniquement que mon nom d'utilisateur mais elle n'indique pas mes informations.
C'est pourquoi, je ne peux pas postuler aux masters, n'ayant pas accès à mes informations.

Comment peut-on remédier à la situation ?

Cordialement 
Noemie SEVA
L3 Droit Université Lumière Lyon 2
n°2171898

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,
