### ISSUE TITLE
Problème de connexion ecandidat Lyon 1 !

### ISSUE THREAD

**Issue by VincentSTAPS** [EsupPortail/esup-ecandidat#24]
Madame, Monsieur,

Je me permets de vous contacter suite à un problème constater sur la plateforme e-candidat Lyon 1.
En effet, étant étudiante à Lyon 1, il me suffit normalement de me connecter pour voir l'ensemble de mon profil (parcours, cursus) s'afficher.
Néanmoins, ce n'est pas le cas actuellement. En effet, lors de la connexion, la plateforme ne reconnaît uniquement que mon nom d'utilisateur mais elle n'indique pas mes informations.
C'est pourquoi, je ne peux pas postuler aux masters, n'ayant pas accès à mes informations.

Comment peut-on remédier à la situation ?

Cordialement
VACALU Vincent 
L3 STAPS Management des Organisations Sportives 
p1700639

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,
