### ISSUE TITLE
Problème connexion eCandidat

### ISSUE THREAD

**Issue by Nihal68** [EsupPortail/esup-ecandidat#25]
Bonjour,
En me connectant sur eCandidat, le site me reconnait mais n'affiche aucune de mes informations ni mes candidatures, ce qui m'empêche de les compléter. 
Pouvez-vous régler ça au plus vite?

Daphné Vorburger
Université de Strasbourg

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,
