### ISSUE TITLE
Désistement par lot et/ou automatique une fois la date de confirmation passée

### ISSUE THREAD

**Issue by rouvoy** [EsupPortail/esup-ecandidat#26]
Serait-il possible de faire en sorte que les candidatures puissent être sélectionnées par lot pour être désistées par le gestionnnaire ?

De même, une fois la date de confirmation passée, les candidatures non-confirmées devraient pouvoir être désistées automatiquement.

**Comment by khergalant** [comment]
Bonjour,

Le désistement est une action candidat et non gestionnaire, elle ne sera pas ajouté à la liste des actions par lot.

Il existe déjà un batch désistant automatiquement les candidats : BATCH_DESIST_AUTO.

Cordialement,
