### ISSUE TITLE
côté client : perte de communication avec le serveur --> blocage user

### ISSUE THREAD

**Issue by f4gbv** [EsupPortail/esup-ecandidat#27]
ecandidat AMU : https://ident.univ-amu.fr/cas/login
(exemple user "E0W2J1EO" du 07/09/2020 au 12/09/2020)
(terminal = win10 Firefox 80.0.1 - ovh  )

Création user ok
1ère connexion ok
...
perte de connexion
-> impossible de se reconnecter une 2e fois. "mauvais identifiant / mot de passe"
demandes multiples de renouvellement password, en vain.
suppression cache net local. 
demandes de renvoi user+pass.
le user semble bloqué.
pas de nettoyage auto des threads inactifs.
load balancing?
Ticket n°323638 ouvert sur esup-helpdesk (ent.univ-amu)
aucun retour d'1 admin . 
Cdlt.
IT.

**Comment by khergalant** [comment]
Bonjour,

Désolé mais je ne comprends pas votre question.

Cordialement,
