### ISSUE TITLE
Récupération réponses formulaire Limesurvey

### ISSUE THREAD

**Issue by svaysset** [EsupPortail/esup-ecandidat#28]
Bonjour,
j'ai installé une instance de Limesurvey sur mon site (version 3.25.16) et j'utilise eCandidat 2.3.1. Malgré la procédure suivante (https://www.esup-portail.org/wiki/pages/viewpage.action?pageId=514523155), je n'arrive pas à récupérer les réponses. J'ai tenté de forcer la synchro du batch Limesurvey, sans succès. J'ai bien activé l'interface RPC (JSON ou XML) sur Limesurvey mais rien y fait.
Merci par avance pour votre aide.
Bonne journée.

**Comment by khergalant** [comment]
Bonjour,

Il faut que l'utilisateur ai les droits de lecture des formulaires.
Menu Configuration --> Gérer les administrateurs de questionnaire.
Sur une ligne d'utilisateur qui doit lire les réponse cliquer sur "Définir des permissions globales pour cet utilisateur".
Puis cliquer en haut à droite sur la double flèche.
Autoriser l'export sur les questionnaires pour cet utilisateur.

Cordialement,

**Comment by khergalant** [comment]
Bonjour,

Le problème est-il résolu?

Cordialement,

**Comment by svaysset** [comment]
Bonjour, 
malgré vos explications, l'utilisateur est bien configuré comme demandé mais cela ne fonctionne pas.
Quel est le protocole de communication utilisé entre eCandidat et Limesurvey pour cette fonctionnalité ? http ? https ?
En vous remerciant.

**Comment by svaysset** [comment]
Bonjour,
j'ai toujours un problème d'import des réponses d'enquête Limesurvey.
Voici les logs de eCandidat:
10:42:05.874 [http-nio-8080-exec-3] TRACE vaysset fr.univlorraine.ecandidat.controllers.rest.LimeSurveyRest - Exception thrown in method 'exportResponse' of class [fr.univlorraine.ecandidat.controllers.rest.LimeSurveyRest]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<?xml version="1.0" encoding="UTF-8"?>
<methodResponse><fault><value><struct><member><name>faultCode</name><value><int>631</int></value></member><member><name>faultString</name><value><string>Failed to parse request</string></value></member></struct></value></fault></methodResponse>"; line: 1, column: 2]

En vous remerciant

**Comment by khergalant** [comment]
Bonjour,

Désolé mais comme ça je ne sais pas.
Avez vous posé la question sur la liste ecandidat-utilisateurs? Peut être que d'autres personnes étaient dans le même cas que vous et ont réussi à le faire fonctionner.

Cordialement,
