### ISSUE TITLE
validation d'une candidature qui est possible, lorsque un formulaire Limesurvey obligatoire n'a pas été rempli.

### ISSUE THREAD

**Issue by tmichel07** [EsupPortail/esup-ecandidat#29]
Bonjour,

Je rencontre un problème avec la validation d'une candidature qui est possible, lorsque un formulaire Limesurvey obligatoire n'a pas été rempli.

En effet, j'ai créé dans ecandidat l'ajout d'un formulaire complémentaire Limesurvey. J'ai décoché la case "conditionnel".

Mais lorsque je crée une candidature, et que je ne rempli pas le formulaire Lime Survey, je peux malgré tout soumettre ma candidature, alors que le formulaire est obligatoire.

Je pensais que la procédure était identique à celle des pièces jointes.  Cad lorsque on crée une piece jointe obligatoire (en décochant la case "conditionnel"). Le candidat doit alors impérativement telecharger cette pièce. S'il essaie de valider sa candidature sans l'avoir téléchargé ,un message d'erreur s'affiche lui rappelant qu'il doit fournir cette PJ.

Mais il n'y a aucun message de ce type lorsque le formulaire Lime Survey n'est pas rempli. Le candidat peut valider sa candidature sans avoir rempli le formulaire , ce qui est très ennuyeux puisque celui ci est requis.

Avez vous une solution ou une suggestion pour remedier à ce problème ? Est-ce une mauvaise utilisation/parametrage de ma part ou un bug ?
en vous remerciant.

J'utilise la Version 3.17.3+190429  de Limesurvey.

**Comment by khergalant** [comment]
Bonjour,

C'est fait et ce sera dans le prochaine release.

Cordialement,
