### ISSUE TITLE
Mise à jour du champ commentaire retour des commissions

### ISSUE THREAD

**Issue by nathalieserra** [EsupPortail/esup-ecandidat#3]
Nous sommes en version 2.2.7.

Lors d'une saisie de commentaire retour pour une commission, nous avons toujours le caractère <br> en fin de ligne sur ce commentaire. Il est donc reproduit sur le dossier de candidature.

De plus, des caractères apparaissent également si l'on veut une mises en forme -centrer, justifier...-Ils ne peuvent plus être enlevés par cet écran de saisie, même en supprimant la mise en forme. Le bouton Remove Formatting est sans effet . Idem pour les champs xml après un copier/coller de word.

Merci de votre aide

Nathalie Serra

**Comment by khergalant** [comment]
Bonjour,

Normalement ça devrait être ok pour la version 2.2.8 : suppression des balises HTML et XML.

Cordialement,

**Comment by khergalant** [comment]
Bonjour,

C'est corrigé, je clos ce ticket.

Cordialement,
