### ISSUE TITLE
Exécution de code javascript personnalisé

### ISSUE THREAD

**Issue by j-kwan** [EsupPortail/esup-ecandidat#30]
Bonjour,

Il y a-t-il moyen de déposer quelque part du code javascript (que ce soit en bdd, via une interface web, ou en fichier) pour que celui-ci soit exécutable via le navigateur du candidat pendant la navigation ?

Nous avons plusieurs instances d'ecandidat déployer dans notre établissement et nous aimerions pouvoir apporter quelque modifications mineures d'affichage/comportement à certains endroits de l'outil. 

J'ai essayé d'insérer des blaises html dans le message `cnil.mention` présent dans `i18n/messages.properties` pour tenter de modifier la page d'accueil. La balise script est bien présente dans le code source, mais celui-ci n'est pas pris en compte par le navigateur.

J'ai pu ajouter quelques instructions dans `styles.css` du template pour modifier l'affichage, mais il faudrait que je puisse par exemple compléter certaines informations affichées avec des informations provenant d'outils tiers grâce à des requêtes xhr.

Bien à vous,

**Comment by khergalant** [comment]
Bonjour,

Désolé du délai de réponse.
Il n'est pas possible d'ajouter du Javascript dans l'application.

Cordialement,
