### ISSUE TITLE
Demande de blocage de la transmission si le formulaire n'est pas renseigné

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-ecandidat#31]
Bonjour,
Nous avons commencé à utiliser les formulaires complémentaires dans le cadre de la collecte de voeux sur le recrutement de nos M1.
Le problème que nous rencontrons est que l'absence de réponse au formulaire ne bloque pas la transmission.
De fait, le formulaire étant obligatoire, il est nécessaire qu'il soit correctement renseigné pour que le dossier soit considéré comme complet.
Il faudrait donc pouvoir bloquer le bouton Transmettre ma candidature tant que le formulaire n'est pas Transmis.
Merci d'avance.
Cordialement,
Yoann Lecuyer

**Comment by khergalant** [comment]
Bonjour,

C'est déjà fait et ce sera dans la prochaine release.

Cordialement,

**Comment by yoannlecuyer** [comment]
Bonjour,
Juste pour en savoir sur le fonctionnement de ce qui sera livré, est ce qu'une solution sera aussi prévue pour que le formulaire soit détecté automatiquement Transmis après le remplissage par le candidat ?
Car si ce n'est pas le cas, le candidat doit alors attendre le lendemain que la synchro avec LimeSurvey se fasse ce qui peut poser problème en fin de campagne de recrutement.
Cordialement,
Yoann

**Comment by khergalant** [comment]
Salut Yoann,

Comment veux tu que je fasse une chose pareil? Il n'y a que le batch qui peut réaliser ceci.
C'est pour cette raison que je n'ai pas bloqué la transmission en cas de non réponse du candidat.

J'ai ajouté un paramétrage pour bloquer ou non la transmission si des formulaires ne sont pas remplis.
Par contre tu peux régler les batchs pour qu'ils s'exécutent plusieurs fois par jour.
La transmission restent une action manuelle du candidat.

a+

**Comment by yoannlecuyer** [comment]
Kevin,
Ma question était plus celle d'un fonctionnel qu'un technique.
En effet, du point de vue du fonctionnel, le besoin est d'avoir un fonctionnement sur le formulaire complémentaire identique à celui des pièces justificatives à savoir, pouvoir répondre au formulaire obligatoire (souvent en dernier) et pouvoir transmettre la candidature dans la lancée.
De fait, je vais surement opter pour une exécution du batch régulier. Sais-tu quel est la fréquence minimum que peuvent supporter eCandidat et LimeSurvey pour une 20-30aine de formulaires ?
Merci d'avance.
Yoann

**Comment by khergalant** [comment]
Non, je ne sais pas, nous n'utilisons pas les formulaires.
je pense qu'une bonne indication est la durée du traitement en environnement de prod. Si ça dure 1min, je pense que tu peux synchroniser fréquemment, si ça dure 2h, ça me parait compliqué.

Pour le coup ça dépend de beaucoup d'éléments (capacité de eCandidat, capacité de limesurvey, votre infra en générale, etc..).

**Comment by yoannlecuyer** [comment]
ok, dans ce cas je vais demander sur la liste de diff.
Yoann
