### ISSUE TITLE
Export / Import des données utilisateurs

### ISSUE THREAD

**Issue by Marmotte69** [EsupPortail/esup-ecandidat#32]
Bonjour,
Serait-il possible à l'avenir de pouvoir exporter localement ses données enregistrées sur un portail afin de les importer plus facilement sur tous les autres portails déployés et ne pas devoir tous les remplir manuellement ?
Bien cordialement.

**Comment by khergalant** [comment]
Bonjour,

Je ne comprends pas votre demande. Pouvez vous préciser?

Cordialement,

**Comment by Marmotte69** [comment]
Bonjour, 

Il s'agirait de d'avoir la possibilité pour un.e candidat.e d'exporter les données (Informations personnelles, Adresse, Baccalauréat, Cursus Interne, Cursus Externe, Stages et Expériences professionnelles) qu'iel a saisi sur le portail d'une université afin de pouvoir les importer lors d'autres candidatures adressées à d'autres universités et ne plus les ressaisir à chaque fois.

Bien à vous.

**Comment by khergalant** [comment]
Bonjour,

Etant donné qu'une synchronisation peut être effectué avec le SI scolarité, il ne sera pas possible d'exporter ces données.

Cordialement,
