### ISSUE TITLE
Batch de nettoyage des locks étudiants

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-ecandidat#33]
Bonjour,
J'ai constaté dernièrement que certains locks étudiants restaient plusieurs jours ou semaines.
Serait-il possible de créer un batch qui supprime les locks de plus de 1 jour ?
Merci d'avance.
Yoann

**Comment by khergalant** [comment]
Bonjour,

Tu peux supprimer les locks de plus de 24h dans Sessions->Lock candidats

Cordialement,
