### ISSUE TITLE
Lien direct vers une candidature ou un dossier d'étudiant

### ISSUE THREAD

**Issue by j-kwan** [EsupPortail/esup-ecandidat#34]
Bonjour,

Existe-t-il un moyen d'accéder directement à :
- une candidature
- un dossier de candidat via le code candidat
svp ?

Il serait fort intéressant dans l'optique de faciliter le travail de nos gestionnaires de pouvoir intégrer des "interconnexions" entre nos outils d'avoir la possibilité de pointer directement sur ces éléments.
À titre d'exemple, nous pouvions directement pointer sur le dossier d'un étudiant sur MonDossierWeb via le lien de la forme 
_http://mondossierweb.domain.tld/mdw/#!link/accesDossierEtudiant/XXXXXXXX_

Bien à vous,

**Comment by cyrilbourreau** [comment]
Je ne sais pas si c'est possible sur eCandidat, j'ai cherché mais pas trouvé, par contre je note votre astuce pour accéder directement à un dossier étudiant, merci beaucoup !

**Comment by khergalant** [comment]
Bonjour,

Désolé ce n'est pas possible.

Cordialement,

**Comment by j-kwan** [comment]
Bonjour,
Désolé de rouvrir ce ticket.
Je comprends que cette fonctionnalité n'existe pas dans la version actuelle.
Serait-il envisageable de l'ajouter aux listes de futures fonctionnalités svp ?
Bien à vous,
