### ISSUE TITLE
Question technique sur les pièces justificatives "commune" et "unique" sur eCandidat V2

### ISSUE THREAD

**Issue by cyrilbourreau** [EsupPortail/esup-ecandidat#35]
Bonjour,

je suis gestionnaire de scolarité de l'UFR Arts & médias à l'université de la Sorbonne Nouvelle.
Avec ma responsable de scolarité, nous mettons en place chaque année la plateforme eCandidat V2.

Nous sommes confrontés à une problématique dont ni le Pôle Scolarité centrale ni l'équipe technique informatique de l'université ne trouvent de réponse. Je me permets alors, de ma propre initiative, de vous soumettre le problème. Il concerne les pièces justificatives et les options "Pièce commune" et "Pièce unique".

Je vais prendre un exemple concret pour vous expliquer le problème :

Nous souhaitons dans un premier temps que sur des formations en Licence 3 la pièce "Relevés de notes de L2" soit demandée. Logiquement nous ne demandons cette pièce qu'à partir d'une candidature en Licence 3 et ne doit donc pas apparaître dans une candidature en L2 et encore moins en L1.

Dans un deuxième temps, nous voudrions que cette pièce "Relevés de notes de L2" n'ait à être versée qu'une seule fois si le candidat candidate à plusieurs formations différentes en L3. Le relevé de notes sera en effet le même strictement.
Selon les explications d'eCandidat, pour arriver à ce résultat, il faut que les cases "Pièce commune" et "pièce unique" soient décochées :

- "Pièce commune" décochée car on ne veut pas que cette pièce soit demandée sur toutes les formations, comme on l'a expliqué précédemment.
- "Pièce unique" décochée puisque l'on veut que le même relevé de notes versé sur une candidature en L3 se retrouve automatiquement ensuite si l'étudiant effectue une autre candidature en L3 (pour une autre mineure ou parcours)

Le problème survient alors : la pièce justificative ajoutée dans l'une des formations en L3 n'apparaît pas dans une autre formation en L3 et le candidat doit donc à chaque fois renvoyer le fichier.

Pour que la fonction de "la pièce unique décochée" fonctionne il faut apparemment cocher la fonction "pièce commune", mais nous ne pouvons pas le faire car sinon on se retrouverait à avoir cette pièce demandée dans toutes les formations, ce que nous ne voulons donc pas.

Nous nous posions alors la question de savoir s'il y avait une anomalie dans les paramétrages d'eCandidat de notre université ou si ce que nous cherchons à faire exactement n'est tout simplement pas possible ?

En vous remerciant par avance et restant à votre disposition pour tout renseignement complémentaire.

Bien cordialement,

Cyril BOURREAU
Gestionnaire de Scolarité
UFR Arts & médias
Université Sorbonne Nouvelle

**Comment by khergalant** [comment]
Bonjour,

Effectivement c'est une évolution intéressante.
Les pièces uniques ne sont effectivement demandées qu'une seule fois que si elles sont communes.

Je vais voir ce que je peux faire à ce sujet.

Cordialement,

**Comment by cyrilbourreau** [comment]
Bonjour Monsieur,
je vous remercie pour votre réponse.
Bien cordialement,

**Comment by khergalant** [comment]
Bonjour,

Ne souhaitant pas modifier le fonctionnement de l'outil sur ce point, je clos ce ticket.

Cordialement,
