### ISSUE TITLE
site e candidat université de montpelier paul valery hs depuis le 26 juillet 

### ISSUE THREAD

**Issue by nadoissandre** [EsupPortail/esup-ecandidat#39]
Bonjour

Depuis une maj effectue par votre service, sauf erreur le 26 juillet aucun etudiant ne peut acceder aux suivis de ces demandes de candidatures 
de nombreux etudiants etaient en liste attente 
pouvez vous regler le probleme qui est problematique et MAJEUR pour permettre aux candidats d'accepter ou refuser les propositions 
https://candidatures.univ-montp3.fr/ecandidat/#!accueilView

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'université de Montpelier.

Cordialement,

**Comment by nadoissandre** [comment]
> Bonjour,
> 
> Vous n'êtes pas au bon endroit pour ce genre de demande.
> Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'université de Montpelier.
> 
> Cordialement,



> Bonjour,
> 
> Vous n'êtes pas au bon endroit pour ce genre de demande.
> Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'université de Montpellier.
> 
> Cordialement,

bonjour merci pour l'information

je me doute mais tout est ferme jusqu'au 23 aout, mais la vie continue et des milliers etudiants sont en attente, et leurs vies ne se sont pas arretees, car il faut trouver un logement demenage ect donc desesperée j'ai clique sur aide du site et de rebond en rebond je suis tombe sur votre nom car a priori vous avez modifie le site le 26 juillet

**Comment by nadoissandre** [comment]
juste pour terminer notre entretien et encore une fois milles excuses si je suis venue vous interpeler ici mais votre nom est apparu dans les logs sur le site aide indique par universite de montpellier 

est ce normal que le e-candidat de universite 3 montpellier paul valery soit ferme alors que sur les autres e candidat, on peut visualiser la suite des demandes de candidatures et voir si on a une proposition ou un refus ou l'avancee sur la liste attente

si tout est normal que ce soit le souhait que le site soit ferme pouvez vous me le confirmer ?

**Comment by khergalant** [comment]
Désolé, je ne peux pas vous aider, je ne travaille pas à l'université de Montpellier.

Cordialement,
