### ISSUE TITLE
Dysfonctionnement validation des avis en masse

### ISSUE THREAD

**Issue by nathalieserra** [EsupPortail/esup-ecandidat#4]
Bonjour

Nous constatons un bug sur la validation des avis en masse, mais nous n'arrivons pas à trouver la cause, ni la séquence fonctionnelle. Sur une même commission, des validations en masse fonctionnent, puis ne fonctionnent plus (seul un avis est validé), puis refonctionnent.
A priori, ce n'est pas lié au candidat, ni à la formation, ni à la commission.
Nous continuons nos recherches, mais depuis hier nous ne reproduisons pas systématiquement le bug.
Merci de votre aide
Cordialement
Nathalie Serra

**Comment by khergalant** [comment]
Bonjour,

Avez vous pu trouver un moyen pour reproduire le bug?

Merci
