### ISSUE TITLE
Problème au moment du build, plugin inaccessible

### ISSUE THREAD

**Issue by abapseres** [EsupPortail/esup-ecandidat#40]
Bonjour, 
Nous avons tenté de faire un build de l'application depuis une nouvelle machine et cela ne fonctionne pas en raison d'un repository inaccessible (voir trace ci-dessous). On est obligé importer le répertoire manuellement dans le cache de maven.
Cordialement 

ERROR] Failed to execute goal org.reflections:reflections-maven:0.9.9-RC2:reflections (default) on project ecandidat: Execution default of goal org.reflections:reflections-maven:0.9.9-RC2:reflections failed: Plugin org.reflections:reflections-maven:0.9.9-RC2 or one of its dependencies could not be resolved: Failed to collect dependencies at org.reflections:reflections-maven:jar:0.9.9-RC2 -> org.jfrog.jade.plugins.common:jade-plugin-common:jar:1.3.8: Failed to read artifact descriptor for org.jfrog.jade.plugins.common:jade-plugin-common:jar:1.3.8: Could not transfer artifact org.jfrog.jade.plugins.common:jade-plugin-common:pom:1.3.8 from/to jfrog-plugins (http://repo.jfrog.org/artifactory/plugins-releases): authorization failed for http://repo.jfrog.org/artifactory/plugins-releases/org/jfrog/jade/plugins/common/jade-plugin-common/1.3.8/jade-plugin-common-1.3.8.pom, status: 403 Forbidden -> [Help 1]

**Comment by khergalant** [comment]
Bonjour,
Effectivement un plugin a disparu du repository maven central.
Pouvez vous remplacer dans le pom.xml le plugin :
`<plugin>
				<groupId>org.reflections</groupId>
				<artifactId>reflections-maven</artifactId>
				<version>0.9.9-RC2</version>
				<configuration>
					<destinations>${project.build.directory}/generated-persistenceinfo/reflections.xml</destinations>
				</configuration>
				<executions>
					<execution>
						<phase>process-classes</phase>
						<goals>
							<goal>reflections</goal>
						</goals>
					</execution>
				</executions>
			</plugin>`

Avec :
`<plugin>
			    <groupId>org.codehaus.gmavenplus</groupId>
			    <artifactId>gmavenplus-plugin</artifactId>
			    <version>1.13.0</version>
			    <executions>
			        <execution>
			            <phase>process-classes</phase>
			            <goals>
			                <goal>execute</goal>
			            </goals>
			            <configuration>
			                <scripts>
			                    <script><![CDATA[
			                        new org.reflections.Reflections("fr.univlorraine.ecandidat")
			                            .save(project.build.directory +"/generated-persistenceinfo/reflections.xml")
			                    ]]></script>
			                </scripts>
			            </configuration>
			        </execution>
			    </executions>
			    <dependencies>
			        <dependency>
			            <groupId>org.reflections</groupId>
			            <artifactId>reflections</artifactId>
			            
			            <version>0.10.2</version>
			        </dependency>
			        <dependency>
			            <groupId>org.codehaus.groovy</groupId>
			            <artifactId>groovy-all</artifactId>
			            
			            <version>2.4.7</version>
			            <scope>runtime</scope>
			        </dependency>
			        <dependency>
					    <groupId>dom4j</groupId>
					    <artifactId>dom4j</artifactId>
					    <version>1.6.1</version>
					</dependency>
			    </dependencies>
			</plugin>`

**Comment by abapseres** [comment]
Bonjour, 
ça fonctionne nickel, merci pour l'information

Cordialement

**Comment by khergalant** [comment]
Bonjour,

Très bien, merci du retour, cela sera intégré dans la prochaine release.

Cordialement,
