### ISSUE TITLE
Impossible de candidater

### ISSUE THREAD

**Issue by HugoM7OL** [EsupPortail/esup-ecandidat#42]
Bonjour, je me permets de vous écrire car je souhaiterai candidater à une formation sur le site https://ecandidat.univ-lyon1.fr/. Cependant lorsque je me connecte et que j'arrive sur la liste des formations je ne peux pas cliquer dessus afin de candidater alors que les inscriptions sont ouvertes. Est ce normal ?
Cordialement
Hugo Martin

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,
