### ISSUE TITLE
Envoi involontaire d'une candidature incomplète suite à un beug

### ISSUE THREAD

**Issue by 8558Mathilde** [EsupPortail/esup-ecandidat#46]
HELP : J'étais en train de réaliser une candidature quand mon navigateur a freezé, j'ai donc forcé la fermeture de la fenêtre et quand je suis revenue sur e-Candidat ensuite, ma candidature incomplète avait été envoyée, je ne peux pas la modifier ni la supprimer. Comment je fais ? 

Bien cordialement

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,
