### ISSUE TITLE
Dernier diplôme non renseigné dans l'extraction des candidatures

### ISSUE THREAD

**Issue by ENIT-ecandidat** [EsupPortail/esup-ecandidat#47]
Constat : Dans l'extraction des candidatures, les informations 'Dernier Diplome' et 'Dernier diplome (libellé)' ne sont pas renseignées quand, dans le cursus Post-Bac, le pays sélectionné est différent de France.

Attente: dans l'extraction des candidatures (accessible via menu Commission / Candidatures), pour les candidats, avec un cursus se déroulant à l'étranger, indiquer

dans Dernier Diplome : la valeur saisie dans Formation (cf. écran cursus Post Bac)
dans Dernier diplome (libellé) : la valeur saisie dans Libellé et niveau de la formation (cf. écran cursus Post Bac)

**Comment by khergalant** [comment]
Bonjour,
Cette fonctionnalité a été ajoutée dans la 2.4.5 qui a été livrée ce jour.
Cordialement,
