### ISSUE TITLE
Demande d'évolution sur l'extraction des candidatures

### ISSUE THREAD

**Issue by ENIT-ecandidat** [EsupPortail/esup-ecandidat#48]
Bonjour,

Demande d'évolution : 

Dans l'extraction des candidatures (menu Commissions / Candidatures), les informations relatives au bac ne sont pas présentes actuellement (nous avons la version 2.3.14 en production, nous passerons à la version Pégase en septembre/octobre 2023). 
Ces informations sont nécessaires à notre service d'admissions pour qu'il puisse procéder à l'examen des candidatures.

Pouvez-vous ajouter, dans l'export excel des candidatures, les colonnes suivantes:

Année obtention Bac
Série du bac
Mention
Spécialité 1
Spécialité 2
Option 1
Option 2
Option 3
Option 4

Cordialement,

Jean-Marc Viret
ENIT - CSN

**Comment by khergalant** [comment]
Bonjour,
Cette fonctionnalité a été ajoutée dans la 2.4.5 qui a été livrée ce jour.
Cordialement,
