### ISSUE TITLE
Integrer le régime étudiant et le statut étudiant dans les OPI

### ISSUE THREAD

**Issue by haberstrau** [EsupPortail/esup-ecandidat#49]
Bonjour

Pour l'université Paris-Saclay, notre plus grand souhait d'évolution serait de pouvoir intégrer le régime et le statut de l'étudiant dans les OPI et donc pouvoir autoriser un gestionnaire à rajouter ces informations comme action possible sur un dossier de candidature et que ces informations soient ensuite ajoutées dans les OPI.
Bien cordialement
Marianne Haberstrau

**Comment by khergalant** [comment]
Bonjour,

Cette fonctionnalité sera disponible dans la 2.4.2 dans l'écran d'administration du candidat : saisie du régime et du statut.
Puis déversé dans l'opi si renseigné.

Cordialement,

**Comment by khergalant** [comment]
Bonjour,

Cette fonctionnalité est disponible.

Cordialement,
