### ISSUE TITLE
Edition source HTML des messages

### ISSUE THREAD

**Issue by DanielBrittain-AMU** [EsupPortail/esup-ecandidat#55]
Est-il possible de pouvoir éditer la source du message d’accueil directement en HTML ?

![image](https://user-images.githubusercontent.com/130745598/231993013-316b4393-3205-48a7-91f8-bbbb895b800f.png)

**Comment by khergalant** [comment]
Bonjour,

Non désolé, ce n'est pas possible.

Cordialement,
