### ISSUE TITLE
Colonnes cachées dans export Excel

### ISSUE THREAD

**Issue by vinriviere** [EsupPortail/esup-ecandidat#57]
eCandidat permet d'exporter les listes de candidatures au format Excel. Il permet également de sélectionner les champs à exporter. Mais les champs non sélectionnés sont tout de même exportés sous forme de colonnes cachées. C'est un problème de confidentialité. Il faut que les champs non cochés ne soient pas exportés du tout.

**Comment by khergalant** [comment]
Bonjour,
Cette fonctionnalité a été ajoutée dans la 2.4.5 qui a été livrée ce jour.
Cordialement,

**Comment by vinriviere** [comment]
Merci, ça marche 😃
