### ISSUE TITLE
Absence des dossiers en attente pour les membres de commissions

### ISSUE THREAD

**Issue by yoannlecuyer** [EsupPortail/esup-ecandidat#64]
Depuis cette année, on constate que les membres de commission ne peuvent plus voir les dossiers en attente.

Bien que ce comportement paraisse normal sur le principe où on ne traite pas un dossier qui n'a pas été envoyé, les membres de commissions m'affirment qu'ils pouvaient les consulter les années précédentes.

S'agit-il d'un nouvelle fonctionnalité qui n'a pas été mentionnée sur les changelog ou s'agit-il d'un bug ?

Merci d'avance

**Comment by yoannlecuyer** [comment]
Pour info, l'alerte m'a été remonté par des enseignants qui ne voient aucune candidature dans leurs espaces. Du coup, il y a une inquiétude à J+30 après le lancement de la campagne, d'avoir des candidats sur leurs formations.

Après échange avec mes collègues, voici 2 propositions de fonctionnalités qui pourraient répondre aux besoins des enseignants : 
- dans l'espace du membre de commission, par exemple à coté du nombre de candidature(s) visisble(s), il faudrait indiquer le nombre de candidatures en attente. Cela permettrait ainsi d'afficher le nombre potentiel de dossiers à traiter
- à la manière de la relance d'avis favorable, il faudrait faire une relance de transmission de la candidature. Il y aurait alors un mail à paramétrer ainsi qu'un champs multivalué indiquant les délais avant date de transmission auxquels eCandidat envoie le mail

**Comment by khergalant** [comment]
Bonjour Yoann,

La visibilité des candidatures pour l'écran de commission se paramètre dans le menu Scolarité Centrale --> Nomenclature --> Type de statut de dossier. Cocher ou décocher "Visible dans l'écran commission".

Kevin

**Comment by yoannlecuyer** [comment]
Bonjour Kevin,
Merci pour l'info, j'étais passé à coté.
Ca a été mis en place dans quelle version ?
Yoann

**Comment by khergalant** [comment]
Bonjour Yoann,

Ca date d'un moment. A vue de nez 2.2.0.

Kevin

**Comment by yoannlecuyer** [comment]
Assez surprenant. Ca veut peut être dire qu'un gestionnaire de notre DEVE a fait la modification.
A creuser en interne.
Yoann

**Comment by yoannlecuyer** [comment]
Bonjour Kevin,
Je me permet de réouvrir (à moins que tu veuilles que je fasse une autre issue à ce sujet) pour resoumettre les propositions suivantes : 
- dans l'espace du membre de commission, par exemple à coté du nombre de candidature(s) visisble(s), il faudrait indiquer le nombre de candidatures en attente. Cela permettrait ainsi d'afficher le nombre potentiel de dossiers à traiter
- à la manière de la relance d'avis favorable, il faudrait faire une relance de transmission de la candidature. Il y aurait alors un mail à paramétrer ainsi qu'un champs multivalué indiquant les délais avant date de transmission auxquels eCandidat envoie le mail
Chez nous, cela soulève un débat sur la nécessité d'afficher ou non les dossiers en attente aux membres de commissions et ces 2 propositions pourraient aider à cadrer les choses, notamment la relance.

**Comment by yoannlecuyer** [comment]
Précision, il pourrait être intéressant que la relance soit paramétrable par formation pour cibler les formations qui pourraient être en flux tendu.

**Comment by khergalant** [comment]
Bonjour Yoann,

Je me le note, mais c'est un gros boulot pour le batch, pas sûr que j'ai le temps de faire une évo comme celle ci rapidement.
Pour plus de clarté, pourrais tu faire 2 tickets et fermer celui-ci?

Merci

**Comment by yoannlecuyer** [comment]
Bonjour Kevin,
Je fais ça.
Yoann
