### ISSUE TITLE
eCandidat - Etablissement introuvable

### ISSUE THREAD

**Issue by CharlieDebuyser** [EsupPortail/esup-ecandidat#7]
Bonjour,

au moment d’ajouter un nouveau cursus externe dans eCandidat, je ne peux pas trouver l’établissement dans lequel j’ai effectué ce dernier : l’IAE de Lille.
Ni l’IAE, ni l’Université de Lille 1 auquel il est rattaché ne figurent dans vos bases de données.

Impossible d’ajouter un Cursus sans sélectionner un établissement dans cette liste, ce qui me condamne à sélectionner un établissement au hasard ne reflétant pas du tout celui dans lequel j’ai été formé, ou bien ne pas ajouté de cursus du tout.

J'ajouterai que les développeurs de l'application sont difficilement trouvable. Un système de maintenance aurait sa place sur l'application.

Pouvez-vous m’aider ?

Par avance merci,

Charlie Debuyser

**Comment by khergalant** [comment]
Bonjour,

Merci de contacter directement l'établissement chez qui vous avez candidaté.

Cordialement,
