### ISSUE TITLE
eCandidat 2.4.5 - Question Endpoint ODF - Pégase V24

### ISSUE THREAD

**Issue by bhuet-insalyon** [EsupPortail/esup-ecandidat#70]
Bonjour, 

Le endpoint ODF mentionné dans le fichier de template (https://github.com/EsupPortail/esup-ecandidat/blob/f566d9e2d063029dc426a7e2d8491157d153a75e/src/main/resources/configUrlServicesPegase.sample.properties#L34) pour la V2.4.5 est celui ci : 

https://odf.univ.fr/api/odf/v1/

Y-a-t-il une raison de ne pas utiliser celui externe ( https://odf.univ.fr/api/odf/ext/v1/ ) à la place ? 

Je vous remercie. 

Bonne journée,

**Comment by khergalant** [comment]
Bonjour,

Il s'agit de l'url que m'a indiqué pc-scol pour le bon fonctionnement de eCandidat, je ne peux pas vous en dire plus.

Bonne journée,

Kevin

**Comment by bhuet-insalyon** [comment]
Bonjour, 
Pas de souci, nous allons creuser de notre côté la question auprès de PC SCOL, et j'actualiserai cette issue au besoin. 
Merci, 
Bonne journée,

**Comment by bhuet-insalyon** [comment]
Bonjour, 
Je viens d'avoir un retour de PC SCOL suite à mon ticket (SP-5123). Ils me confirment que c'est bien l'API externe d'ODF qui doit être utilisée et non celle interne. Ils vont prendre contact avec vous d'ici peu pour vous transmettre l'information. 
Je vous souhaite une excellente journée,

**Comment by khergalant** [comment]
Bonjour,

Effectivement cela fonctionne avec l'api ext/ins.

Je vais prévenir les utilisateurs.

Bonne journée,

Kevin
