### ISSUE TITLE
Export des candidatures : se termine par une ligne "test"

### ISSUE THREAD

**Issue by vinriviere** [EsupPortail/esup-ecandidat#71]
Depuis le passage à eCandidat 2.4.5, quand on exporte une liste de candidatures, il y a le mot "test" qui apparaît tout en bas, après deux lignes vides. Je suppose que c'est un oubli : il faut enlever ce mot.

**Comment by khergalant** [comment]
Bonjour,

Effectivement c'est un oubli.
Cela sera corrigé dans la 2.4.6.

Cordialement,

**Comment by khergalant** [comment]
Bonjour,

C'est corrigé dans la 2.4.6.

Cordialement,

**Comment by vinriviere** [comment]
Merci Kévin, ça marche.
