### ISSUE TITLE
Variable nom et prénom

### ISSUE THREAD

**Issue by mael-agro** [EsupPortail/esup-ecandidat#79]
Bonjour 

Je souhaite récupérer le Nom et Prénom des candidats  dans un formulaire limesurvey comment on le fait aujourd'hui pour les numéros de dossier,

Est-ce qu'il est possible d'ajouter c'est variable .

Merci d'avance

**Comment by khergalant** [comment]
Bonjour,

Cela sera disponible dans la 2.4.7 en utilisant les variables ${nom} et ${prenom}.

**Comment by khergalant** [comment]
Bonjour,

C'est ajouté dans la 2.4.7 qui a été livrée ce matin.

Cordialement,
