### ISSUE TITLE
loadbalancing. "Erreur de communication avec le serveur" avant la connexion

### ISSUE THREAD

**Issue by D-u-f-f-y** [EsupPortail/esup-ecandidat#8]
Bonjour
Nous somme en Ecandidat 2.2.9, mode loadbalancing avec un frontal apache, 2 serveurs étudiant, 1 serveur gestionnaire.
Chaque fois on va sur le côté étudiant, avant la connexion, on voit un bandeau noir avec un message "Erreur de communication avec le serveur", on peut quand même cliquer ce bandeau 1 ou 2 fois pour le faire disparaitre et continuer sur ECandidat.
Dans le console on a "SEVERE: Response didn't contain a server id. Please verify that the server is up-to-date and that the response data has not been modified in transmission."
voici la config apache sur le frontal:

        Header add Set-Cookie "ROUTEID=.%{BALANCER_WORKER_ROUTE}e; path=/" env=BALANCER_ROUTE_CHANGED

        <Proxy "balancer://ecandidatpushhttp">
        BalancerMember http://xxx.xxx.x.98:8081/PUSH route=candidatpushhttp1 keepalive=On smax=1 connectiontimeout=10 retry=600 timeout=900 ttl=900
        BalancerMember http://xxx.xxx.x.99:8081/PUSH route=candidatpushhttp2 keepalive=On smax=1 connectiontimeout=10 retry=600 timeout=900 ttl=900
        ProxySet  stickysession=ROUTEID nofailover=Off
        </Proxy>

        RewriteEngine on
        RewriteCond %{QUERY_STRING} ^((?!X-Atmosphere-Transport=websocket).)*$
        RewriteRule "^/PUSH(.*)$"  "balancer://ecandidatpushhttp$1" [P]
        <Proxy "balancer://ecandidatpush">
        BalancerMember ws:// http://xxx.xxx.x.98:8081/PUSH route=candidatpush1 keepalive=On retry=0
        BalancerMember ws:// http://xxx.xxx.x.99:8081/PUSH route=candidatpush2 keepalive=On retry=0
        ProxySet  stickysession=ROUTEID nofailover=Off
        </Proxy>
        ProxyPass "/PUSH" "balancer://ecandidatpush"
        ProxyPassReverse "/PUSH" "balancer://ecandidatpush"

       
        ProxyPass "/" "balancer://ecandidat/"

        <Proxy balancer://ecandidat>
        BalancerMember ajp:// http://xxx.xxx.x.98:8009 route=candidat1 keepalive=On smax=1 connectiontimeout=10 retry=600 timeout=900 ttl=900
        BalancerMember ajp:// http://xxx.xxx.x.99:8009 route=candidat2 keepalive=On smax=1 connectiontimeout=10 retry=600 timeout=900 ttl=900
        ProxySet  stickysession=ROUTEID nofailover=Off
        </Proxy>
Avez vous une idée svp?
Merci

**Comment by khergalant** [comment]
Bonjour,

N'ayant pas d'informations à fournir, je clos ce ticket.
Vous pouvez vous adresser à la liste de diffusion.

Cordialement,
