### ISSUE TITLE
Augmenter le champs login du candidat (login_cpt_min)

### ISSUE THREAD

**Issue by labretagne** [EsupPortail/esup-ecandidat#80]
sur la nouvelle version les champs prénom et nom ont une capacité max de 40 caractères mais le champs de login, souvent composé de prenom.nom est resté à 60 max, pourriez vous l'augmenter à 80 ?

**Comment by khergalant** [comment]
Bonjour,

Je ne sais pas où vous avez trouvé ces valeurs mais cela ne correspond pas. Et il n'y a eu aucune modification dans la nouvelle version.

Les login gestionnaires sont limités à 50 caractères, les login candidat à 30 caractères.
Ca me parait déjà énorme pour des logins..

**Comment by labretagne** [comment]
Bonjour, je parlais de cette augmentation là https://github.com/EsupPortail/esup-ecandidat/issues/76 mais effectivement j'avais regardé la taille des champs dans notre bdd et pas dans les sources.
Nous n'avons pas de soucis avec les identifiants des gestionnaires en effet, mais par contre plusieurs comptes d'étudiants ont des identifiants > 30 caractères , il suffit d'un "prenom composé" . "nom un peu long" et la limité est franchie. N'est il pas possible de les limiter à 60 comme les gestionnaires?
Cordialement
