### ISSUE TITLE
Modifier l'ordre des colonnes dans l'affichage de l'offre de formation

### ISSUE THREAD

**Issue by labretagne** [EsupPortail/esup-ecandidat#86]
Bonjour,
est ce possible de modifier ou de rendre possible la modification de l'ordre des colonnes dans l'affichage de l'offre de formation? les dates juste après le titre.
![Image20241217110540](https://github.com/user-attachments/assets/acaf9810-3043-4205-9646-ab480b78faca)

Cordialement

**Comment by khergalant** [comment]
Bonjour,

Oui c'est possible en modifiant le paramètre odfColonne. Par exemple : 
<Parameter name="odfColonne" value="dates:200;motCle:200;url:300;modeCand:100" />

**Comment by labretagne** [comment]
merci beaucoup, je n'avais pas vu ce paramétrage possible
