### ISSUE TITLE
chargement pièce jointe

### ISSUE THREAD

**Issue by AurelieTr** [EsupPortail/esup-ecandidat#9]
Impossibilité de charger les pièces justificatives demandées malgré la taille du format respecté et format pdf.

**Comment by MaximeGuil** [comment]
Bonjour,
Même problème pour moi
Sachant que mon inscription se termine demain je ne sais même pas comment transmettre mes documents 
Quelqu'un a déjà eu ce problème ?
Merci.

**Comment by ChrystelleG** [comment]
Même problème ici aussi... Je ne sais pas trop quoi faire !

**Comment by MaximeGuil** [comment]
J'ai réussi a mettre mes documents.
Mais il a fallut que j'insiste pendant une bonne heure. Essayez de reduire la taille des documents au maximum aussi on sait jamais, pour moi ca a marché. Alors que j'étais très en dessous de la limite...

**Comment by Horpheun** [comment]
Toujours impossible pour moi malheureusement :/

**Comment by ChrystelleG** [comment]
Pareil pour moi... T'as réussi à charger quelques fichiers ou rien du tout ?

**Comment by andreeaaf** [comment]
Impossible de télécharger les pièces jointes aussi.... Quelqu'un aurait une solution car il ne reste plus beaucoup de temps

**Comment by Horpheun** [comment]
@ChrystelleG  Non Malheureusement rien, ecandidat marchant pour certaine Université mais pour une précisément (Lyon 2) impossible :/

**Comment by Morgane2165902** [comment]
Bonjour. Nous sommes quelques autres étudiantes à rencontrer le même problème depuis Vendredi. Sachant que nous avions que jusqu'à hier pour télécharger ces pièces.

**Comment by khergalant** [comment]
Bonjour,

Vous n'êtes pas au bon endroit pour ce genre de demande.
Ecandidat est installé dans une soixantaine d'établissements, merci de contacter directement l'établissement dans lequel vous avez candidaté.

Cordialement,
